# Bin collection schedule configuration
collection_day_of_week: 4 # Thursday
bins:
  - color: "ðŸŸ¦ Blue"
    start_date: "2025-06-05"
    cycle_weeks: 4
  - color: "ðŸŸ© Green"
    start_date: "2025-06-05"
    cycle_weeks: 1
  - color: "ðŸŸ« Brown"
    start_date: "2025-06-05"
    cycle_weeks: 4
  - color: "â¬› Black"
    start_date: "2025-06-12"
    cycle_weeks: 2