# Bin collection schedule configuration
collection_day_of_week: 4 # Thursday
bins:
  - color: "Blue"
    start_date: "2025-06-05"
    cycle_weeks: 4
  - color: "Green"
    start_date: "2025-06-05"
    cycle_weeks: 1
  - color: "Brown"
    start_date: "2025-06-05"
    cycle_weeks: 4
  - color: "Black"
    start_date: "2025-06-12"
    cycle_weeks: 2

weather:
  latitude: 53.371208
  longitude: -2.188037
  timezone: "Europe/London"
  location_name: "Cheadle Hulme, UK"


restaurants:
  - name: "The Golden Gate"
    opening_hours:
      monday: [ "12-2pm", "4:30-9pm" ]
      tuesday: "Closed"
      wednesday: [ "12-2pm", "3:30-9pm" ]
      thursday: [ "12-2pm", "4:30-9pm" ]
      friday: [ "12-2pm", "3:30-1pm" ]
      saturday: "4:30-10pm"
      sunday: "16:30-9pm"
  - name: "Healthy & Delicious"
    opening_hours:
      monday: "5-10pm"
      tuesday: "Closed"
      wednesday: "5-10pm"
      thursday: "5-10pm"
      friday: "5-10:30pm"
      saturday: "5-10:30pm"
      sunday: "5-10pm"
  - name: "Jalfrezi"
    opening_hours:
      monday: "5-11pm"
      tuesday: "5-11pm"
      wednesday: "5-11pm"
      thursday: "5-10pm"
      friday: "5-11:30pm"
      saturday: "5-11:30pm"
      sunday: "5-11pm"
  - name: 'Sizzling Wok'
    opening_hours:
      monday: "5-10pm"
      tuesday: "5-10pm"
      wednesday: "Closed"
      thursday: "5-10pm"
      friday: "5-10pm"
      saturday: "5-10pm"
      sunday: "5-10pm"

venues:
  - name: "Chads Theatre"
    url: "https://www.ticketsource.co.uk/chads"
    events:
      - name: "Dangerous Corner"
        playwright: "J.B. Priestley"
        start_date: "2026-01-24"
        end_date: "2026-01-31"
        description: "A play about truth and consequences in a successful publishing business."
      - name: "Blackbird"
        playwright: "David Harrower"
        start_date: "2026-02-24"
        end_date: "2026-02-28"
        description: "A hard-hitting drama inspired by real events, performed in the studio."
      - name: "The Birthday Party"
        playwright: "Harold Pinter"
        start_date: "2026-03-14"
        end_date: "2026-03-21"
        description: "Post-war classic mixing comedy and menace in a seaside boarding house."
      - name: "Constellations"
        playwright: "Nick Payne"
        start_date: "2026-04-14"
        end_date: "2026-04-18"
        description: "A love story across parallel universes exploring choices and chance."
      - name: "A Midsummer Night’s Dream"
        playwright: "William Shakespeare"
        start_date: "2026-05-09"
        end_date: "2026-05-16"
        description: "Shakespeare’s enchanting comedy of love, magic, and mischief."
  - name: "CHS"
    url: "https://www.ticketsource.co.uk/Cheadlehulmeschool"
    events:
      - name: "Shrek The Musical Jr"
        playwright: ""
        start_date: "2026-02-10"
        end_date: "2026-02-13"
        description: ""