calendar:
  green_weeks:
    - '2026-01-19'
    - '2020-02-02'
    - '2026-02-24'
    - '2026-03-09'
    - '2026-03-23'
    - '2026-04-20'
    - '2026-05-04'
    - '2026-05-18'
    - '2026-06-08'
    - '2026-06-22'
  yellow_weeks:
    - '2026-02-12'
    - '2026-05-26'
    - '2026-02-09'
    - '2026-03-03'
    - '2026-03-16'
    - '2026-04-13'
    - '2026-04-27'
    - '2026-05-11'
    - '2026-06-01'
    - '2026-06-15'


