restaurants:
  - name: "The Golden Gate"
    closed: [ "tue" ]
  - name: "Healthy & Delicious"
    closed: [ "tue" ]
  - name: 'Sizzling Wok'
    closed: [ "wed" ]
  - name: "Jalfrezi"
    closed: [ ]
